[package]
name = "macro_testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc_macros = { path = "./proc_macros" }

[workspace]
members = [
    ".",
    "proc_macros"
]

